import { useEffect, useState } from 'react'
import api from '../../services/api'
import { Spinner, statusLabel } from '../common'
import MarkdownLite from './MarkdownLite'

/**
 * The Explain / Elaborate panel.
 *
 * The request names a scope; the backend rebuilds the deterministic evidence
 * for it and asks the LLM to describe it. When the LLM is unavailable the panel
 * says so plainly -- it never shows an invented explanation, and the rest of
 * the dashboard is unaffected.
 */
export default function ExplainPanel({ request, onClose }) {
  const [state, setState] = useState({ loading: true, result: null, error: null })

  useEffect(() => {
    if (!request) return undefined
    const controller = new AbortController()
    let active = true

    setState({ loading: true, result: null, error: null })
    api
      .explain(request, controller.signal)
      .then((result) => active && setState({ loading: false, result, error: null }))
      .catch((error) => {
        if (!active || error.name === 'AbortError') return
        setState({ loading: false, result: null, error })
      })

    return () => {
      active = false
      controller.abort()
    }
  }, [request])

  if (!request) return null

  const { loading, result, error } = state

  // Colour tells the "was this just generated, or reused" story instead of
  // a "cached" label: green for a fresh call to the LLM just now, red for
  // an earlier answer reused because nothing about this selection has
  // changed. Neither loading nor an unavailable result carries either tone
  // -- there is nothing generated or reused to signal yet.
  const tone = result?.available ? (result.cached ? 'cached' : 'fresh') : null

  return (
    <section
      className={tone ? `explain explain--${tone}` : 'explain'}
      title={
        tone === 'fresh'
          ? 'Just generated by the AI for this exact selection.'
          : tone === 'cached'
            ? 'Reused from an earlier identical request -- nothing about this selection has changed, so no new AI call was made.'
            : undefined
      }
    >
      <div className="explain__head">
        <h3 className="explain__title">AI explanation — {describeScope(request)}</h3>
        <button type="button" className="btn btn--ghost" onClick={onClose}>
          Close
        </button>
      </div>

      {loading ? (
        <div className="explain__body" style={{ color: 'var(--text-muted)' }}>
          <Spinner /> Generating an explanation from the deterministic evidence…
        </div>
      ) : null}

      {error ? (
        <Unavailable message={error.message} />
      ) : null}

      {result && !result.available ? <Unavailable message={result.error} /> : null}

      {result?.available ? (
        <div className="explain__body">
          <MarkdownLite text={result.explanation} />
        </div>
      ) : null}

      {result?.evidence?.summary ? (
        <details style={{ marginTop: 12 }}>
          <summary style={{ cursor: 'pointer', fontSize: 12, color: 'var(--text-muted)' }}>
            Evidence sent to the model
          </summary>
          <pre
            style={{
              marginTop: 9,
              maxHeight: 300,
              overflow: 'auto',
              fontSize: 11.5,
              background: 'var(--bg-raised)',
              border: '1px solid var(--border)',
              borderRadius: 6,
              padding: 11,
            }}
          >
            {JSON.stringify(result.evidence, null, 2)}
          </pre>
        </details>
      ) : null}
    </section>
  )
}

function Unavailable({ message }) {
  return (
    <div className="explain__body">
      <strong>AI explanation unavailable.</strong>
      {'\n'}The underlying daily task data is still available and unchanged.
      {message ? `\n\n${message}` : ''}
    </div>
  )
}

/** Names the scope from narrowest key to broadest, matching the drill-down. */
function describeScope(request) {
  if (request.task_daily_id) return `task on well ${request.well_id ?? ''}`.trim()
  if (request.well_id) return `well ${request.well_id}`

  const parts = []
  if (request.status) parts.push(statusLabel(request.status))
  if (request.wbs) parts.push(request.wbs)
  if (request.activity_code) parts.push(request.activity_code)
  if (parts.length) return parts.join(' · ')

  if (request.uom) return `UOM ${request.uom}`
  return `all daily work on ${request.report_date}`
}
