import { useEffect, useState } from 'react'
import api from '../../services/api'
import { Spinner, statusLabel } from '../common'
import MarkdownLite from './MarkdownLite'

/**
 * The Explain / Elaborate panel.
 *
 * The request names a scope; the backend rebuilds the deterministic evidence
 * for it and asks the LLM to describe it. When the LLM is unavailable the panel
 * says so plainly -- it never shows an invented explanation, and the rest of
 * the dashboard is unaffected.
 */
/**
 * One in-flight explanation per identical request, shared by every caller.
 *
 * This is the client-side half of the backend's per-(date, evidence) lock, and
 * it exists for a bug that lock cannot fix from its side. React's development
 * StrictMode mounts each component twice, so opening a panel fired the request
 * twice: the first was aborted by the cleanup, the second arrived after the
 * backend had already generated and cached the answer -- and came back marked
 * as cached. The very first time an operator opened a well's summary, the
 * panel therefore said "reused". The answer was honest about what the second
 * request got; the second request was the problem.
 *
 * Sharing the promise means the remount joins the request already running
 * rather than starting another, so the response the panel shows is the one
 * that was actually generated for it. A genuinely later request -- reopening
 * the panel, another well, another date -- finds nothing in flight and asks
 * again, and is then correctly told the answer was cached.
 */
const inFlight = new Map()

function requestExplanation(key) {
  const existing = inFlight.get(key)
  if (existing) return existing
  // Deliberately not abortable: aborting never stopped the backend from
  // finishing and caching the work anyway, and it is what made a fresh
  // answer look reused. A superseded response is discarded by the caller
  // instead -- see the `active` flag below.
  const pending = api.explain(JSON.parse(key)).finally(() => inFlight.delete(key))
  inFlight.set(key, pending)
  return pending
}

export default function ExplainPanel({ request, onClose }) {
  const [state, setState] = useState({ loading: true, result: null, error: null })

  // Keyed on the values that identify the request rather than on the object
  // itself: a caller that rebuilds an equivalent object on every render would
  // otherwise re-fire this effect, asking for the same explanation again.
  const requestKey = request ? JSON.stringify(request) : null

  useEffect(() => {
    if (!requestKey) return undefined
    let active = true

    setState({ loading: true, result: null, error: null })
    requestExplanation(requestKey)
      .then((result) => active && setState({ loading: false, result, error: null }))
      .catch((error) => {
        if (!active || error.name === 'AbortError') return
        setState({ loading: false, result: null, error })
      })

    return () => {
      active = false
    }
  }, [requestKey])

  if (!request) return null

  const { loading, result, error } = state

  // Colour says whether this text was just generated or reused, instead of a
  // "cached" label. A reused answer is green: nothing underneath it has
  // changed since it was written, which is the reassuring case and the one
  // worth marking. A fresh generation gets the panel's ordinary styling --
  // it is the normal thing to happen, not a status to flag, and colouring it
  // would imply something had gone wrong or been spent. Neither loading nor
  // an unavailable result carries a tone: there is nothing generated or
  // reused yet to signal.
  //
  // `cached` is read from the response exactly as the backend reports it
  // (ExplainResponse.cached), never inferred from timing or from having asked
  // before: only the backend knows whether its own evidence hash hit the
  // cache, and a first generation must never be able to look like a reuse.
  const cached = Boolean(result?.available && result.cached)

  return (
    <section
      className={cached ? 'explain explain--cached' : 'explain'}
      title={
        result?.available
          ? cached
            ? 'Reused from an earlier identical request -- nothing about this selection has changed, so no new AI call was made.'
            : 'Generated by the AI just now for this exact selection.'
          : undefined
      }
    >
      <div className="explain__head">
        <h3 className="explain__title">AI explanation — {describeScope(request)}</h3>
        <button type="button" className="btn btn--ghost" onClick={onClose}>
          Close
        </button>
      </div>

      {loading ? (
        <div className="explain__body" style={{ color: 'var(--text-muted)' }}>
          <Spinner /> Generating an explanation from the deterministic evidence…
        </div>
      ) : null}

      {error ? (
        <Unavailable message={error.message} />
      ) : null}

      {result && !result.available ? <Unavailable message={result.error} /> : null}

      {result?.available ? (
        <div className="explain__body">
          <MarkdownLite text={result.explanation} />
        </div>
      ) : null}

      {/*
        Three ways to check the same answer, each collapsed so the panel stays
        skimmable:

        * the evidence, which is exactly what the model was given;
        * the SQL those figures came from, as it is actually executed;
        * the individual task records behind the counts, with the reason each
          one is counted.

        The model never sees the last two. It is handed finished figures, and
        showing it the query would only invite it to reason about SQL instead
        of explaining what the query already decided.
      */}
      {result?.evidence && Object.keys(result.evidence).length ? (
        <details className="explain__drawer">
          <summary className="explain__drawer-summary">
            What is sent to AI model for summary
          </summary>
          {result.evidence_withheld_from_model?.length ? (
            <div className="explain__note">
              Returned below for audit but deliberately not sent to the model:{' '}
              {result.evidence_withheld_from_model.join(', ')} — there was nothing in it
              for the model to describe.
            </div>
          ) : null}
          <pre className="explain__pre">{JSON.stringify(result.evidence, null, 2)}</pre>
        </details>
      ) : null}

      {result?.sql_sources?.length ? (
        <details className="explain__drawer">
          <summary className="explain__drawer-summary">SQL</summary>
          <div className="explain__note">
            The queries these figures came from, as executed. The report date travels as a
            bound parameter and is never spliced into the text, so it is listed beside each
            query rather than shown inside it.
          </div>
          {result.sql_sources.map((source) => (
            <div key={source.file} className="explain__sql">
              <div className="explain__sql-head">
                {source.label}
                <span className="explain__sql-file">{source.file}</span>
              </div>
              {source.parameters?.length ? (
                <div className="explain__sql-params">{source.parameters.join(' · ')}</div>
              ) : null}
              <pre className="explain__pre">{source.sql}</pre>
            </div>
          ))}
        </details>
      ) : null}

      {result?.proof?.length ? (
        <details className="explain__drawer">
          <summary className="explain__drawer-summary">
            Proof — the {result.proof.length} open task
            {result.proof.length === 1 ? '' : 's'} behind these counts
          </summary>
          <div className="explain__note">
            Every task not recorded as completed, and which of the row's two figures it
            counts toward — the two do not overlap, so they add up to the total. The reason
            restates what that task's own record says; it is not an interpretation of it.{' '}
            {result.proof_note || ''}
          </div>
          <div className="explain__table-wrap">
            <table className="proof-table">
              <thead>
                <tr>
                  <th scope="col">Well</th>
                  <th scope="col">Task</th>
                  <th scope="col">Schedule</th>
                  <th scope="col" className="proof-table__description">Description</th>
                  <th scope="col">Incomplete</th>
                  <th scope="col">Ongoing</th>
                  <th scope="col">Actual start</th>
                  <th scope="col">Actual end</th>
                  <th scope="col">Last task date</th>
                </tr>
              </thead>
              <tbody>
                {result.proof.flatMap((row, index) => [
                  <tr key={`${row.task_code}-${row.schedule_id ?? index}`}>
                    <td>{row.well_id}</td>
                    <td className="proof-table__code">
                      {row.task_code || <span className="missing">Not recorded</span>}
                    </td>
                    <td>{row.schedule_id ?? <span className="missing">—</span>}</td>
                    <td className="proof-table__description">
                      {row.description || row.activity_code || (
                        <span className="missing">Not mapped</span>
                      )}
                    </td>
                    <td className="proof-table__flag">{row.counts_as_incomplete ? 'Yes' : 'No'}</td>
                    <td
                      className={
                        row.counts_as_ongoing
                          ? 'proof-table__flag task-state--ONGOING'
                          : 'proof-table__flag'
                      }
                    >
                      {row.counts_as_ongoing ? 'Yes' : 'No'}
                    </td>
                    <td>{row.actual_start || <span className="missing">—</span>}</td>
                    <td>{row.actual_end || <span className="missing">—</span>}</td>
                    <td>{row.last_task_date || <span className="missing">—</span>}</td>
                  </tr>,
                  /*
                    The reason gets the full width of the table rather than a
                    tenth of it: it is the column an operator opened this for,
                    and squeezed into a narrow cell beside nine others it
                    wrapped into an unreadable ribbon.
                  */
                  <tr key={`${row.task_code}-${row.schedule_id ?? index}-why`} className="proof-table__why">
                    <td colSpan={9}>{row.reason}</td>
                  </tr>,
                ])}
              </tbody>
            </table>
          </div>
        </details>
      ) : null}
    </section>
  )
}

function Unavailable({ message }) {
  return (
    <div className="explain__body">
      <strong>AI explanation unavailable.</strong>
      {'\n'}The underlying daily task data is still available and unchanged.
      {message ? `\n\n${message}` : ''}
    </div>
  )
}

/** Names the scope from narrowest key to broadest, matching the drill-down. */
function describeScope(request) {
  if (request.task_daily_id) return `task on well ${request.well_id ?? ''}`.trim()
  if (request.well_id) return `well ${request.well_id}`

  const parts = []
  if (request.status) parts.push(statusLabel(request.status))
  if (request.wbs) parts.push(request.wbs)
  if (request.activity_code) parts.push(request.activity_code)
  if (parts.length) return parts.join(' · ')

  if (request.uom) return `UOM ${request.uom}`
  return `all daily work on ${request.report_date}`
}
